import {
  REACT_APP_LOGIN,
  REACT_APP_REGISTER,
  REACT_APP_USER,
  REACT_APP_BASE_URL,
  REACT_APP_RECIPE,
  REACT_APP_CATEGORY,
} from '@env';

export default {
  REACT_APP_LOGIN,
  REACT_APP_REGISTER,
  REACT_APP_USER,
  REACT_APP_BASE_URL,
  REACT_APP_RECIPE,
  REACT_APP_CATEGORY,
};
